### ISSUE TITLE
Add convenient way to filter records for Remote Settings Client

### ISSUE THREAD

**Issue by Vishwa-Mozilla** [mozilla-services/remote-settings-client#1]
**Motivation:** Enable users to find a particular record by providing id. This enhancement adds convenience for the user in case they want to filter records by id. Add Unit testing along with the change.

**Comment by Vishwa-Mozilla** [comment]
## Solution 1: 
Add get(expected: u64, filter: serde_json::Value) and get_all(expected: u64) methods to Client; get_all() function returns all the records back to the user; get() function returns records matching the provided filter JSON Value

**Pros:**
- User does not have to worry about filtering the records and it frees them from testing the filtering logic

**Cons:**
- More work for Remote-Settings library but other than that it leads to a cleaner experience to the users

## Solution 2:
Add get() that returns all the records back to the user and the user can filter them

**Pros:**
- Less work for Remote-Settings Client and allows users to do customized filtering or anything with the result

**Cons:**
- More work for users since they will have to look up how to filter JSON values and also add testing for the filter functionality

**Comment by leplatrem** [comment]
What about Solution 3, which would consist of returning a custom type extending vectors, with a `filter()` method?

```
let all = client.get().await?;
let record = all.filter("id", "some-id")[0]
```
