### ISSUE TITLE
Add storage feature

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/remote-settings-client#27]
**Goal**

* Add «cache» (or storage) feature to `.get()`

This will be pave the way for synchronization features. 

**Behaviour**

* If storage is empty for this bucket/collection, fetch from `.../changeset`, validate signature, store locally, and return records
* Otherwise, obtain current remote timestamp of collection from server (done in #26)
* If remote timestamp is different than local, fetch, validate signature, overwrite local existing data and return records
* If remote timestamp is same as local, validate signature and return records. If validating signature fails, fetch, validate, overwrite, and return records.

**Definition of done**

* A storage abstraction (pluggable) with a default implementation. This default implementation could be very «stupid» (eg. store as folders `{bucket}/{collection}.json`)
* Unit tests should cover almost 100% of situations
* Documentation etc.

**Notes**

* This storage abstraction could take `(bucket, collection)` as constructor and have only two methods (`store(metadata, timestamp, records)`  and `retrieve() -> {metadata, timestamp, records}`)
* When adding synchronization **later**, instead of fetching and overwriting everything locally, we'll fetch partial changes from `/changeset?_since=<local-timestamp>` and add the necessary complexity in the storage abstraction (tombstones, etc).
* We could follow the pattern of #37, where a dummy storage is a no-op, have a storage that writes files on disk, and choose storage feature from config (in the future we could have storage implementations in DB, indexeddb, rkv, ...)

**Comment by Vishwa-Mozilla** [comment]
Design for this issue depends on Issue #19 

Questions?
- Do we need to make caching an optional feature?

**Approach**: Create Remote-Settings-Storage Trait which contains **store(struct)** and retrieve(struct) where struct encompasses bucket, collection, metadata, timestamp, records
- Similar to pluggable verification logic in current code

**Pros:**
- Easy to test
- Customizable
- Dependency Injection

**Cons:**
- Don't see any

**Comment by Vishwa-Mozilla** [comment]
@leplatrem what are your thoughts?

**Comment by leplatrem** [comment]
> Do we need to make caching an optional feature?

Yes. For example, I don't think the WDBA remote switch use-case would need one.
We could provide, dummy, in-memory, and on-disk for example.

> Do we feel safe storing signatures anywhere the storage implementation wants to?

Yes, signatures are public strings, so it's safe (unlike private keys).


You say that Trait objects are slower than static dispatch, do you have figures? Is it that bad? Could be an interested blogpost topic ;) Anyway, here performance is not an issue, since it will be IO bound. 

Variants of approach 1:

* `storage { config }`, `storage.store({ bucket, collection, metadata, timestamp, records })`, and `storage.retrieve() -> {bucket, collection, metadata, timestamp, records}`
* `storage { config, bucket, collection }`, and `storage.store({ metadata, timestamp, records })`, and `storage.retrieve() -> {metadata, timestamp, records})`

**Comment by ncalexan** [comment]
For storage, please don't make consumers think about the Remote Settings data model.  If you can make it just be "store this JSON" and "provide this JSON back", that's great.  That lets you start with one JSON blob for everything and grow into many JSON blobs as you need to do more fine-grained stuff (like for syncing records).  As a consumer I just want to be able to pipe your opaque blob onto disk and back with as little fuss and thinking about the internals as possible.
